#!/bin/sh
# Assemble the deployable site.
#
# Two things here are load-bearing:
#  1. server-only modules are stripped from the browser bundle
#  2. sw.js gets a BUILD id derived from a CONTENT HASH of the bundle, so the
#     cache name changes exactly when the code does. A date alone would either
#     bust on every deploy (pointless churn) or not at all if reused.
set -e
SRC=/var/minis/repos/ai-mentat-dejavu
OUT=/var/minis/shared/webhost/ai-dejavu-site/ai-dejavu

cd "$SRC"

# Inline the pure-JS extractor sources so exportScript() can embed them without
# a network fetch. Regenerated every build so the export never drifts from src/.
python3 - <<'GEN'
import json, pathlib
photo = pathlib.Path('src/runtime-photo.js').read_text()
mel   = pathlib.Path('src/runtime-mel.js').read_text()
pathlib.Path('src/runtime-src.ts').write_text(
    '/** Generated by build-site.sh - do not edit. */\n'
    f'export const RUNTIME_PHOTO = {json.dumps(photo)};\n'
    f'export const RUNTIME_MEL = {json.dumps(mel)};\n')
GEN

./node_modules/.bin/tsc

mkdir -p site/dist
cp dist/*.js site/dist/
cd site/dist
for f in server cli test test_actions test_media test_backbone test_flow ui; do rm -f "$f.js"; done
rm -f ./*.map
cd "$SRC"

rm -rf "$OUT"
mkdir -p "$OUT"
cp -r site/* "$OUT/"
rm -f "$OUT"/tmtest.html "$OUT"/tmsep.html

# content hash of everything the browser will actually run
HASH=$(cat "$OUT"/dist/*.js "$OUT"/*.html 2>/dev/null | md5sum | cut -c1-12)
BUILD="$(date +%Y-%m-%d_%H-%M)_$HASH"
sed -i "s/__BUILD__/$BUILD/" "$OUT/sw.js"

# _headers must sit at the DEPLOY ROOT, not inside /ai-dejavu, and its paths are
# absolute from that root.
sed 's|^/sw.js|/ai-dejavu/sw.js|; s|^/manifest.webmanifest|/ai-dejavu/manifest.webmanifest|; s|^/dist/\*|/ai-dejavu/dist/*|' \
  _headers_src > /var/minis/shared/webhost/ai-dejavu-site/_headers

echo "BUILD=$BUILD"
grep -c . /var/minis/shared/webhost/ai-dejavu-site/_headers | sed 's/^/_headers lines: /'
