/**
 * Export a trained model as a single self-contained JavaScript file.
 *
 * The point: a trained head is ~1-15 KB of weights, and the `photo` and `mel`
 * extractors are pure JS with ZERO dependencies (photo.ts imports only a type,
 * which is erased at compile time; audio.ts imports nothing). So for those two
 * the whole detector — preprocessing, weights, match rule and actions — fits in
 * one file that runs unmodified in a browser, Node or Bun.
 *
 * The pretrained backbones (tmnet, scnet, dinov2/3) cannot be inlined: they need
 * TensorFlow.js or transformers.js plus 1.6-23 MB of weights from a CDN. Those
 * export a file that loads its runtime on demand and documents the requirement,
 * rather than pretending to be self-contained.
 *
 * Runtime shape, deliberately small:
 *
 *   const d = createDetector({ threshold: .8, targets: ['cat'],
 *                              onMatched: r => ..., onNotMatched: r => ... });
 *   await d.classify(inputImageOrPcm);   // -> { predicted, confidence, probs, matched }
 *
 * Everything else (webhooks, cooldowns, logging) is the caller's business —
 * they get callbacks and can do what they like. That keeps the generated file
 * dependency-free instead of bundling an HTTP client.
 */
import type { StoredModel } from './store.js';

/** Source of the pure-JS extractors, inlined into the generated file. */
export interface ExtractorSource {
  photo?: string;
  mel?: string;
}

const RUNTIME_NOTE: Record<string, string> = {
  photo: 'Self-contained. No dependencies, no downloads.',
  mel: 'Self-contained. No dependencies, no downloads.',
  tmnet: 'Needs @tensorflow/tfjs and downloads MobileNetV2 (~1.6 MB) on first use.',
  scnet: 'Needs @tensorflow/tfjs and downloads speech-commands (~2 MB) on first use.',
  dinov2: 'Needs @huggingface/transformers and downloads DINOv2 (~23 MB) on first use.',
  dinov3: 'Needs @huggingface/transformers and downloads DINOv3 (~21 MB) on first use.',
};

function f32(a: Float64Array | number[]): string {
  // 6 decimals is plenty: the head's inputs are standardised, and it keeps the
  // file readable and small.
  return '[' + Array.from(a).map(v => +v.toFixed(6)).join(',') + ']';
}

export interface ExportOpts {
  /** Compiled source of the extractor this model uses, when it is pure JS. */
  extractorSource?: string;
  /** Name used in comments and the default export. */
  name?: string;
}

export function exportScript(rec: StoredModel, opts: ExportOpts = {}): string {
  const pure = rec.extractor === 'photo' || rec.extractor === 'mel';
  const isAudio = rec.extractor === 'mel' || rec.extractor === 'scnet';
  const name = opts.name ?? `aidejavu-${rec.extractor}`;

  const head = `/**
 * ${name} — generated by AI Déjà Vu on ${new Date().toISOString()}
 *
 * classes    ${rec.classes.join(', ')}
 * extractor  ${rec.extractor} (${rec.dim}-d)
 * trained on ${rec.metrics.nTrain} samples, ${rec.metrics.nTest} held out
 * accuracy   train ${(rec.metrics.train * 100).toFixed(1)}% · test ${(rec.metrics.test * 100).toFixed(1)}%
 *
 * ${RUNTIME_NOTE[rec.extractor] ?? ''}
 *
 * Runs in a browser, Node 18+ or Bun. ESM.
 *
 *   import { createDetector } from './${name}.js';
 *   const d = createDetector({
 *     targets: ${JSON.stringify(rec.classes.slice(0, 1))},
 *     threshold: 0.7,
 *     onMatched:    r => console.log('MATCH', r.predicted, r.confidence),
 *     onNotMatched: r => {},
 *   });
 *   const r = await d.classify(${isAudio
      ? '{ pcm: Float32Array, sampleRate: 16000 }'
      : 'canvasOrImageDataOrHTMLImage'});
 */
`;

  const weights = `
// ---------------------------------------------------------------- model
export const MODEL = {
  classes: ${JSON.stringify(rec.classes)},
  extractor: ${JSON.stringify(rec.extractor)},
  dim: ${rec.dim},
  mu: ${f32(rec.mu)},
  sd: ${f32(rec.sd)},
  W: ${f32(rec.W)},
  b: ${f32(rec.b)},
  metrics: ${JSON.stringify(rec.metrics)},
};
`;

  const inference = `
// ---------------------------------------------------------------- head
/** Standardise, then multinomial logistic regression — the trained part. */
function predict(v) {
  const { dim, classes, mu, sd, W, b } = MODEL;
  if (v.length !== dim) {
    throw new Error('expected a ' + dim + '-d vector, got ' + v.length);
  }
  const z = new Float64Array(dim);
  for (let j = 0; j < dim; j++) z[j] = (v[j] - mu[j]) / sd[j];
  const k = classes.length;
  const logits = new Float64Array(k);
  for (let c = 0; c < k; c++) {
    let s = b[c];
    for (let j = 0; j < dim; j++) s += W[c * dim + j] * z[j];
    logits[c] = s;
  }
  let m = -Infinity;
  for (let c = 0; c < k; c++) if (logits[c] > m) m = logits[c];
  let tot = 0;
  const probs = new Array(k);
  for (let c = 0; c < k; c++) { probs[c] = Math.exp(logits[c] - m); tot += probs[c]; }
  for (let c = 0; c < k; c++) probs[c] /= tot;
  let best = 0;
  for (let c = 1; c < k; c++) if (probs[c] > probs[best]) best = c;
  return { predicted: classes[best], confidence: probs[best], probs, index: best };
}

// ---------------------------------------------------------------- detector
/**
 * @param {object} [opts]
 * @param {string[]} [opts.targets]      classes that count as a match (default: all)
 * @param {number}   [opts.threshold]    minimum confidence, 0..1 (default 0.7)
 * @param {number}   [opts.cooldownMs]   suppress repeat fires per branch (default 0)
 * @param {Function} [opts.onMatched]
 * @param {Function} [opts.onNotMatched]
 */
export function createDetector(opts = {}) {
  const targets = opts.targets && opts.targets.length ? opts.targets : MODEL.classes.slice();
  const threshold = opts.threshold ?? 0.7;
  const cooldownMs = opts.cooldownMs ?? 0;
  const last = { matched: 0, notMatched: 0 };

  // Fail fast on a typo'd target rather than never matching.
  for (const t of targets) {
    if (!MODEL.classes.includes(t)) {
      throw new Error('unknown target "' + t + '"; classes are ' + MODEL.classes.join(', '));
    }
  }

  return {
    model: MODEL,
    /** Classify a pre-computed feature vector. */
    fromVector(v) { return finish(predict(v)); },
    /** Classify a raw input (image-like, or { pcm, sampleRate }). */
    async classify(input) {
      const v = await embed(input);
      return finish(predict(v));
    },
  };

  function finish(res) {
    const matched = targets.includes(res.predicted) && res.confidence >= threshold;
    const out = {
      ...res, matched, threshold, targets,
      probabilities: Object.fromEntries(MODEL.classes.map((c, i) => [c, res.probs[i]])),
      ts: new Date().toISOString(),
    };
    const branch = matched ? 'matched' : 'notMatched';
    const now = Date.now();
    if (cooldownMs > 0 && now - last[branch] < cooldownMs) {
      return { ...out, skipped: 'cooldown' };
    }
    last[branch] = now;
    // A throwing callback must not break the detection loop.
    try {
      const cb = matched ? opts.onMatched : opts.onNotMatched;
      if (cb) cb(out);
    } catch (e) {
      if (typeof console !== 'undefined') console.error('callback threw:', e);
    }
    return out;
  }
}

export default createDetector;
`;

  let extractor: string;
  if (pure && opts.extractorSource) {
    extractor = `
// ---------------------------------------------------------------- extractor
// Inlined ${rec.extractor} extractor: pure JS, no dependencies.
${opts.extractorSource}
`;
  } else if (pure) {
    extractor = `
// ---------------------------------------------------------------- extractor
// NOTE: extractor source was not supplied at export time. Use fromVector()
// with a ${rec.dim}-d vector you compute yourself.
async function embed() {
  throw new Error('no extractor bundled — use fromVector() instead');
}
`;
  } else {
    extractor = `
// ---------------------------------------------------------------- extractor
// ${rec.extractor} needs a pretrained backbone that cannot be inlined.
// ${RUNTIME_NOTE[rec.extractor] ?? ''}
// Compute the ${rec.dim}-d vector with that library, then call fromVector().
async function embed() {
  throw new Error(
    '${rec.extractor} requires its backbone; compute the vector separately ' +
    'and call fromVector(v)');
}
`;
  }

  return head + weights + extractor + inference;
}
